### ISSUE TITLE
[Bug] Broken Links in Readme

### ISSUE THREAD

**Issue by elizabethpeters** [fivetran/dbt_qualtrics#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Links in documentation that have a base url of https://fivetran.github.io/ are broken, resulting in 404 errors.  Links going to other urls and github.com/fivetran/dbt_qualtrics work fine. 

### Expected behavior

Links should open to a correct and working page. 

### dbt Project configurations

n/a

### Package versions

n/a

### What database are you using dbt with?

other (mention it in "Additional Context")

### dbt Version

n/a

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @elizabethpeters thanks so much for opening this issue and for identifying the broken links. These links were broken due to the docs site not being deployed. I just deployed it and the links should be working as expected.

I'll close out this issue as the broken links should be addressed. Also as a resident of Chicago I must say... GO CUBS! 🐐
